# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build PR

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build website content
      env:
        GITHUB_HEAD_SHA: "${{ github.event_name == 'pull_request' && github.event.pull_request.head.sha || '' }}"
      run: |
        runestone build
    - name: Save PR number
      if: github.ref != 'refs/heads/main'
      run: |
        echo ${{ github.event.number }} > ./build/PyZombis/NR
        echo ${{ github.event.pull_request.head.repo.full_name }} > ./build/PyZombis/REPO
    - name: Save branch name
      if: github.ref == 'refs/heads/main'
      run: |
        echo "main" > ./build/PyZombis/NR
    - name: Upload generated content artifact
      uses: actions/upload-artifact@v2
      with:
        name: website-output
        path: build/PyZombis/

  test:

    needs: build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install playwright & browsers
      run: |
        playwright install
    - name: Download generated content artifact
      uses: actions/download-artifact@v2
      with:
        name: website-output
        path: build/PyZombis/
    - name: Serve website locally
      run: |
        runestone serve &
    - name: Run PyTest UTs
      run: |
        pytest --html=report.html --self-contained-html
    - name: Upload test report
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: report.html
        path: report.html
    - name: Upload test videos
      uses: actions/upload-artifact@v2
      if: ${{ always() }}
      with:
        name: videos
        path: videos
